ollama:
  gpu: {}
    # # -- Enable GPU integration
    # enabled: true
    
    # # -- GPU type: 'nvidia' or 'amd'
    # type: 'amd'
    
    # # -- Specify the number of GPU to 1
    # number: 1
   
  # -- List of models to pull at container startup
  models:
    pull:
      # - mistral
      # - Qwen/Qwen2-0.5B-Instruct-GPTQ-Int8
      - nomic-embed-text:latest
service:

  # -- Service type
  type: LoadBalancer