apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: custom-model-config
  namespace: kagent
spec:
  # apiKeySecretRef: kagent-openai
  # apiKeySecretKey: OPENAI_API_KEY
  model: <insert-model-name> # This should match the model name passed to the provider.
  modelInfo:
    functionCalling: true
    family: unknown
  provider: Ollama
  ollama:
    host: http://ollama.ollama.svc.cluster.local
